import com.ninetailsoftware.model.events.HaEvent;

rule "ADT Email Alarm Armed Away"
when
    HaEvent(value contains "Security System Armed Away")
then
    HaEvent ha = new HaEvent();
    ha.setSource("adt");
    ha.setValue("2");
    ha.setDeviceId("18");
    
    insert(ha);
end

rule "ADT Email Alarm Armed Stay"
when
    HaEvent(value contains "Security System Armed Stay")
then
    HaEvent ha = new HaEvent();
    ha.setSource("adt");
    ha.setValue("1");
    ha.setDeviceId("18");
    
    insert(ha);
end

rule "ADT Email Alarm Disarmed"
when
    HaEvent(value contains "Security System Disarmed")
then
    HaEvent ha = new HaEvent();
    ha.setSource("adt");
    ha.setValue("0");
    ha.setDeviceId("18");
    
    insert(ha);
end