import com.ninetailsoftware.model.events.HaEvent;

rule "ADT Email Alarm Armed Away"
when
    HaEvent(value contains "Security System Armed Away") over window:time(1s)
then
    HaEvent ha = new HaEvent();
    ha.setSource("homeseer");
    ha.setValue("2");
    ha.setDeviceId("18");
    ha.setSendUpdate(true);
    
    insert(ha);
end

rule "ADT Email Alarm Armed Stay"
when
    HaEvent(value contains "Security System Armed Stay") over window:time(1s)
then
    HaEvent ha = new HaEvent();
    ha.setSource("homeseer");
    ha.setValue("1");
    ha.setDeviceId("18");
    ha.setSendUpdate(true);
    
    insert(ha);
end

rule "ADT Email Alarm Disarmed"
when
    HaEvent(value contains "Security System Disarmed") over window:time(1s)
then
    HaEvent ha = new HaEvent();
    ha.setSource("homeseer");
    ha.setValue("0");
    ha.setDeviceId("18");
    ha.setSendUpdate(true);    
    
    insert(ha);
end