import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import com.ninetailsoftware.model.facts.SimpleSwitch;
import com.ninetailsoftware.model.events.HaEvent;

rule "Turn off front porch at 0000"
   timer(cron: 0 0 0 * * ?)
when
    SimpleSwitch(id == "54")
then
    HaEvent e = new HaEvent();
    e.setDeviceId("54");
    e.setSource("brms");
    e.setValue("0");
    
    insert(e);
end

rule "Turn on front port at Dusk"

when
    HaEvent(deviceId =="23", value=="2")
then
    HaEvent e = new HaEvent();
    e.setDeviceId("54");
    e.setSource("brms");
    e.setValue("255");
    
    insert(e);
end