import com.ninetailsoftware.model.events.HaEvent;
import com.ninetailsoftware.model.facts.SimpleSwitch;

rule "Goodnight house"
no-loop
   when
       ha : HaEvent( deviceId == "57" && value == "0") over window:length(1)
       s : SimpleSwitch(status != "0" && floor != "Outdoors")
   then
       HaEvent event = new HaEvent();
       event.setDeviceId(s.getId());
       event.setValue("0");
       event.setSource("homeseer");
       event.setSendUpdate(true);
       insert(event);
end

rule "Enable Goodnight house switch"
no-loop
   when
       ha : HaEvent( value != "0") over window:length(1)
       exists (SimpleSwitch(ha.deviceId == id && floor != "Outdoors"))
   then
       HaEvent event = new HaEvent();
       event.setDeviceId("57");
       event.setValue("100");
       event.setSource("homeseer");
       event.setSendUpdate(true);
       insert(event);
end

rule "Enable first floor switch"
no-loop
   when
       ha : HaEvent( value != "0") over window:length(1)
       exists (SimpleSwitch(ha.deviceId == id && floor == "First Floor"))
   then
       HaEvent event = new HaEvent();
       event.setDeviceId("73");
       event.setValue("100");
       event.setSource("homeseer");
       event.setSendUpdate(true);
       insert(event);
end

rule "Enable second floor switch"
no-loop
   when
       ha : HaEvent( value != "0") over window:length(1)
       exists (SimpleSwitch(ha.deviceId == id && floor == "Second Floor"))
   then
       HaEvent event = new HaEvent();
       event.setDeviceId("74");
       event.setValue("100");
       event.setSource("homeseer");
       event.setSendUpdate(true);
       insert(event);
end


rule "1st Level Power"
no-loop
   when
       ha : HaEvent( deviceId == "73" ) over window:length(1)
       s : SimpleSwitch(status != "0" && floor == "First Floor")
   then
       HaEvent event = new HaEvent();
       event.setDeviceId(s.getId());
       event.setValue("0");
       event.setSource("homeseer");
       event.setSendUpdate(true);
       insert(event);
end

rule "2nd Level Power"
no-loop
   when
       ha : HaEvent( deviceId == "74" ) over window:length(1)
       s : SimpleSwitch(status != "0" && floor == "Second Floor")
   then
       HaEvent event = new HaEvent();
       event.setDeviceId(s.getId());
       event.setValue("0");
       event.setSource("homeseer");
       event.setSendUpdate(true);
       insert(event);
end