import com.ninetailsoftware.model.events.HaEvent;
import com.ninetailsoftware.model.facts.SimpleSwitch;

rule "Goodnight house"
   when
       ha : HaEvent( deviceId == "57" ) over window:time(1s)
       s : SimpleSwitch(status != "0" && floor != "Outdoors")
   then
       HaEvent event = new HaEvent();
       event.setDeviceId(s.getId());
       event.setValue("0");
       event.setSource("brms");
       insert(event);
end

rule "1st Level Power"
   when
       ha : HaEvent( deviceId == "73" ) over window:time(1s)
       s : SimpleSwitch(status != "0" && floor == "First Floor")
   then
       HaEvent event = new HaEvent();
       event.setDeviceId(s.getId());
       event.setValue("0");
       event.setSource("brms");
       insert(event);
end

rule "2nd Level Power"
   when
       ha : HaEvent( deviceId == "74" ) over window:time(1s)
       s : SimpleSwitch(status != "0" && floor == "Second Floor")
   then
       HaEvent event = new HaEvent();
       event.setDeviceId(s.getId());
       event.setValue("0");
       event.setSource("brms");
       insert(event);
end