import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import com.ninetailsoftware.model.facts.ElectricOutlet;
import com.ninetailsoftware.model.events.HaEvent;

rule "Turn off holiday lights at 2200"
   timer(cron: 0 0 22 * * ?)
when
    ElectricOutlet(id == "71")
then
    HaEvent e = new HaEvent();
    e.setDeviceId("71");
    e.setSource("homeseer");
    e.setValue("0");
    e.setSendUpdate(true);
    
    insert(e);
end

rule "Turn on holiday lights at 1630"
  timer(cron: 0 30 16 * * ?)
when
    ElectricOutlet(id == "71")
then
    HaEvent e = new HaEvent();
    e.setDeviceId("71");
    e.setSource("homeseer");
    e.setValue("255");
    e.setSendUpdate(true);
    
    insert(e);
end