import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import com.ninetailsoftware.model.facts.ElectricOutlet;
import com.ninetailsoftware.model.events.HaEvent;

rule "Turn off Pergola automatically"
   timer(cron: 0 0 21 * * ?)
when
    ElectricOutlet(id == "296")
then
    HaEvent e = new HaEvent();
    e.setDeviceId("296");
    e.setSource("homeseer");
    e.setValue("0");
    e.setSendUpdate(true);
    
    insert(e);
end

rule "Turn on Pergola at Dusk"

when
    HaEvent(deviceId =="23", value=="2") over window:time(1s)
then
    HaEvent e = new HaEvent();
    e.setDeviceId("296");
    e.setSource("homeseer");
    e.setValue("255");
    e.setSendUpdate(true);
    
    insert(e);
end