import com.ninetailsoftware.model.events.HaEvent;
import com.ninetailsoftware.model.facts.SimpleSwitch;
import com.ninetailsoftware.model.facts.MotionSensor;

rule "Turn Lights On with Motion"
when
    e : HaEvent (e.value == "8") over window:time(5s)
    m : MotionSensor(m.id == e.deviceId )
    s : SimpleSwitch(s.status == "0" && s.floor == m.floor && s.room == m.room)
    not HaEvent(s.id == deviceId, value =="0", this before[0,10s] e)
then
    HaEvent event = new HaEvent();
    event.setDeviceId(s.getId());
    event.setValue("255"); 
    event.setSource("brms");
    insert(event);
end

/**
rule "Turn Off Lights with No Motion"
when
    e : HaEvent (e.value == "0") over window:length(1)
    m : MotionSensor(m.id == e.deviceId)
    s : SimpleSwitch(s.floor == m.floor && s.room == m.room && s.status != 0)
    not (exists HaEvent(m.id == deviceId) over window:time(15m))
then
    HaEvent event = new HaEvent();
    event.setDeviceId(s.getId());
    event.setValue("0"); 
    event.setSource("brms");
    insert(event);
end
*/
/*
rule "Turn Off Office Lights With No Motion"
when
    e1 : HaEvent (value == "0" && deviceId == "32")
    not HaEvent (deviceId == e1.deviceId, value == "8", this after [0,30m] e1)
then
    HaEvent office = new HaEvent();
    office.setValue("0");
    office.setDeviceId("24");
    office.setSource("brms");
    
    insert(office);
end*/