import com.ninetailsoftware.model.events.HaEvent;

rule "Alarm Armed Away"
when
    HaEvent(value contains "System Armed (away mode)") over window:time(1s)
then
    HaEvent ha = new HaEvent();
    ha.setSource("homeseer");
    ha.setValue("2");
    ha.setDeviceId("18");
    ha.setSendUpdate(true);
    
    insert(ha);
end

rule "Alarm Armed Stay"
when
    HaEvent(value contains "System Armed (home mode)") over window:time(1s)
then
    HaEvent ha = new HaEvent();
    ha.setSource("homeseer");
    ha.setValue("1");
    ha.setDeviceId("18");
    ha.setSendUpdate(true);
    
    insert(ha);
end

rule "Alarm Disarmed"
when
    HaEvent(value contains "System Disarmed") over window:time(1s)
then
    HaEvent ha = new HaEvent();
    ha.setSource("homeseer");
    ha.setValue("0");
    ha.setDeviceId("18");
    ha.setSendUpdate(true);    
    
    insert(ha);
end