import com.ninetailsoftware.model.events.HaEvent;
import com.ninetailsoftware.model.facts.AlarmPanel;

rule "Alarm Armed Away"
when
    he : HaEvent(value == "2" && deviceId == "118") over window:time(1s)
    AlarmPanel(he.deviceId == id && he.value != status)
then
    HaEvent ha = new HaEvent();
    ha.setSource("homeseer");
    ha.setValue("2");
    ha.setDeviceId("118");
    ha.setSendUpdate(true);
    
    insert(ha);
end

rule "Alarm Armed Stay"
when
    he : HaEvent(value == "1" && deviceId == "118") over window:time(1s)
    AlarmPanel(he.deviceId == id && he.value != status)
then
    HaEvent ha = new HaEvent();
    ha.setSource("homeseer");
    ha.setValue("1");
    ha.setDeviceId("118");
    ha.setSendUpdate(true);
    
    insert(ha);
end

rule "Alarm Disarmed"
when
    he : HaEvent(value == "0" && deviceId == "118") over window:time(1s)
    AlarmPanel(he.deviceId == id && he.value != status)
then
    HaEvent ha = new HaEvent();
    ha.setSource("homeseer");
    ha.setValue("0");
    ha.setDeviceId("118");
    ha.setSendUpdate(true);    
    
    insert(ha);
end