import com.ninetailsoftware.model.events.HaEvent;
import com.ninetailsoftware.model.facts.Device;

rule "Update Device Status"
no-loop true
salience 10
when
    d : Device ( )
    ha : HaEvent ( d.id == ha.deviceId ) over window:length(1)
    HaEvent(this.deviceId == ha.deviceId) over window:time(1s)
    eval (ha.getValue() != d.getStatus())
then
    d.setStatus(ha.getValue());
    d.setSource(ha.getSource());
    update(d);
end