import com.ninetailsoftware.model.events.HaEvent;
import com.ninetailsoftware.model.facts.Device;

declare HaEvent  
      @role(event)  
      @expires(value = 48h, policy = TIME_SOFT)
end  

rule "Update Device Status"
no-loop true
salience 10
when
    d : Device ( )
    ha : HaEvent ( d.id == ha.deviceId && d.source == ha.source && ha.value != d.status) over window:time(1s)
then
    d.setStatus(ha.getValue());
   	d.setSendUpdate(ha.isSendUpdate());

    update(d);
end