import com.ninetailsoftware.model.events.HaEvent;
import com.ninetailsoftware.model.facts.Device;

declare HaEvent  
      @role(event)  
      @expires(value = 48h, policy = TIME_SOFT)
end  

rule "Update Device Status"
no-loop true
salience 10
when
    d : Device ( )
    ha : HaEvent ( d.id == ha.deviceId && d.source == ha.source && ha.value != d.status) over window:time(1s)
then
    d.setStatus(ha.getValue());
    if(ha.isSendUpdate() != null)
    	d.setSendUpdate(ha.isSendUpdate());
    else
    	d.setSendUpdate(false);
    update(d);
end