import com.ninetailsoftware.model.events.HaEvent;
import com.ninetailsoftware.model.facts.SimpleSwitch;
import com.ninetailsoftware.model.facts.AlarmPanel;
import com.ninetailsoftware.model.facts.TheSun;

rule "Turn 2nd floor hall lights on with motion"
when
    HaEvent (value == "8" && deviceId == "27") over window:time(1s)
    AlarmPanel (status == "2")
    TheSun(status == "0" || status == "2")
then
    HaEvent secondFloorLanding = new HaEvent();
    secondFloorLanding.setValue("33");
    secondFloorLanding.setDeviceId("26");
    secondFloorLanding.setSource("brms");
    
    insert (secondFloorLanding);
end

rule "Turn dining room lights on with motion"
when
    HaEvent (value == "8" && deviceId == "27") over window:time(1s)
    AlarmPanel (status == "2")
    TheSun(status == "0" || status == "2")
then
    HaEvent diningRoom = new HaEvent();
    diningRoom.setValue("33");
    diningRoom.setDeviceId("25");
    diningRoom.setSource("brms");
    
    insert(diningRoom);
end

rule "Turn Off dining room Lights When Noone Enters"
when
    not(exists HaEvent (value == "8" && deviceId == "27") over window:time(1m))
    AlarmPanel (status == "2")
then
    HaEvent diningRoom = new HaEvent();
    diningRoom.setValue("0");
    diningRoom.setDeviceId("25");
    diningRoom.setSource("brms");
    
    insert(diningRoom);
end

rule "Turn Off 2nd floor landing  Lights When Noone Enters"
when
    not(exists HaEvent (value == "8" && deviceId == "27") over window:time(1m))
    AlarmPanel (status == "2")
then
    HaEvent secondFloorLanding = new HaEvent();
    secondFloorLanding.setValue("0");
    secondFloorLanding.setDeviceId("26");
    secondFloorLanding.setSource("brms");
    
    insert (secondFloorLanding);
end